from __future__ import annotations
from typing import Any, List, Optional
from pydantic import BaseModel, Field, HttpUrl, EmailStr, AnyUrl
from enum import Enum
from typing import Optional
from pydantic import BaseModel


class Lang(str, Enum):
    fr = "fr"
    en = "en"
    


class Contact_TypeEnumFr(str, Enum):
    option_1="email"
    option_2="name"
    option_3="formulaire"
    
class Contact_TypeEnumEn(str, Enum):
    option_1="Email"
    option_2="Name"
    option_3="Form"
    

class Dataset_TypeEnumFr(str, Enum):
    option_1="Portail"
    option_2="Jeu de données"
    option_3="Base de données"
    
class Dataset_TypeEnumEn(str, Enum):
    option_1="Portal"
    option_2="Dataset"
    option_3="Database"
    

class EnvironmentEnumFr(str, Enum):
    option_1="Air"
    option_2="Eau"
    option_3="Sols"
    option_4="Alimentation"
    
class EnvironmentEnumEn(str, Enum):
    option_1="Air"
    option_2="Water"
    option_3="Soils"
    option_4="Food"
    

class NatureEnumFr(str, Enum):
    option_1="Biodiversité"
    option_2="Indicateurs géographiques et socio-démographiques"
    option_3="Agents Physiques"
    option_4="Pesticides"
    
class NatureEnumEn(str, Enum):
    option_1="Biodiversity"
    option_2="Geographical and Sociodemographical Indicators"
    option_3="Physical Agents"
    option_4="Pesticides"
    

class SubthematicEnumFr(str, Enum):
    option_1="Accidentologie"
    option_2="Adresses"
    option_3="Amiante naturel en affleurements dans les formations géologiques"
    option_4="Anciens sites miniers français d'uranium"
    option_5="Aérobiologie  Qualité de l'air : pollens et moisissures"
    option_6="Biocides"
    option_7="Bruit"
    option_8="Carroyage"
    option_9="Carte des reliefs"
    option_10="Cartographie des masses d'eau sensibles à la pollution"
    option_11="Cartographie des zones polluées par l'eau"
    option_12="Cartographie du bruit associé aux trafics"
    option_13="Climatologie"
    option_14="Connaissance du paysage pédologique"
    option_15="Contaminants chimiques dans l'alimentation"
    option_16="Contaminants de l'eau"
    option_17="Contours géométriques des IRIS"
    option_18="Déchets radioactifs"
    option_19="Délimitations des parcelles viticoles"
    option_20="Eauxs souterraines"
    option_21="Ecosystèmes forestiers"
    option_22="Emissions atmosphériques des secteurs de l'industrie, du transport,  tertiaire et agricole"
    option_23="Emissions polluantes et Déchets"
    option_24="Exposition aux métaux et activités professionnelles"
    option_25="Exposition des population au bruit"
    option_26="Exposure of individuals and populations in Europe to UV radiation"
    option_27="Fond cartographique"
    option_28="Gestion des déchets,  Développement durable"
    option_29="Géologie"
    option_30="Index des substances phytosanitaires"
    option_31="Indicateurs d'exposition spatialisés agrégés et combinés"
    option_32="Inventaire des dépôts de résidus miniers"
    option_33="Inventaire et cartographie des sols"
    option_34="Limites administratives"
    option_35="Locaux à usage d'habitation"
    option_36="Mesures de bruit"
    option_37="Milieux agricoles"
    option_38="Météorologie"
    option_39="Niveaux d'exposition aux musiques amplifiées du jeune publique"
    option_40="Occupation des sols"
    option_41="Paramètres descriptifs de la population française"
    option_42="Parcelles vitivinicoles"
    option_43="Pesticides dans l'air"
    option_44="Pollution / Contamination des sols"
    option_45="Pollution atmosphérique ambiante"
    option_46="Pollution des eaux souterraines"
    option_47="Propriétés physico-chimiques des sols et occupation des terres"
    option_48="Prévision atmosphérique"
    option_49="Prévision de la chimie atmosphérique et transport"
    option_50="Qualité agronomique des sols"
    option_51="Qualité de l’air : pollution atmosphérique"
    option_52="Qualité des eaux littorales"
    option_53="Qualité de l'air"
    option_54="Qualité de l'air dans les établissements recevant du public"
    option_55="Qualité de l'air et Bruit"
    option_56="Qualité de l'air et acoustique"
    option_57="Qualité de l'eau"
    option_58="Qualité des eaux"
    option_59="Qualité des eaux de surface / Connaissance milieux"
    option_60="Qualité des sols"
    option_61="Qualité des sols urbains"
    option_62="Radioactivité"
    option_63="Radiofréquence"
    option_64="Radon émis par les formations géologiques"
    option_65="Rayonnements ionisants"
    option_66="Recensement des sites naturels/ biodiversité"
    option_67="Référentiel de masse d'eau"
    option_68="Référentiel hydrographique français"
    option_69="Référentiel hydrogéologique français"
    option_70="Réseaux de mesure de stations"
    option_71="Sites et sols pollués"
    option_72="Trafic routier"
    option_73="Ventes de produits phytopharmaceutiques"
    
class SubthematicEnumEn(str, Enum):
    option_1="Accidentology"
    option_2="Addresses"
    option_3="Natural asbestos in tributaries in geological formations"
    option_4="Former French uranium mining sites"
    option_5="Aerobiology Air quality: pollen and mold"
    option_6="Biocides"
    option_7="Bruit"
    option_8="Carroyage"
    option_9="Map of reliefs"
    option_10="Cartography of pollution-sensitive water masses"
    option_11="Water-polluted area mapping"
    option_12="Cartography of noise associated with traffics"
    option_13="Climate"
    option_14="Knowledge of the pedological landscape"
    option_15="Chemical Contaminants in Food"
    option_16="Water Contaminants"
    option_17="Geometric Contours of IRIS"
    option_18="Radioactive waste"
    option_19="Delimitations of vineyards"
    option_20="Groundwater"
    option_21="Forest ecosystems"
    option_22="Air emissions from industry, transport, tertiary and agricultural sectors"
    option_23="Pollutant emissions and wastes"
    option_24="Metal exposure and professional activities"
    option_25="Population exposure to noise"
    option_26="Exposure of individuals and populations in Europe to UV radiation"
    option_27="Cartographic background"
    option_28="Waste management, Sustainable development"
    option_29="Geology"
    option_30="Plant Health Substances Index"
    option_31="Aggregate and combined spatial exposure indicators"
    option_32="Inventory of mine residues"
    option_33="Soil inventory and mapping"
    option_34="Administrative limitations"
    option_35="Residential premises"
    option_36="Noise measures"
    option_37="Agricultural conditions"
    option_38="Weather"
    option_39="Levels of exposure to amplified young public music"
    option_40="Land occupation"
    option_41="Descriptive parameters of the French population"
    option_42="Wine parks"
    option_43="Pesticides in the air"
    option_44="Pollution / Soil contamination"
    option_45="Ambient air pollution"
    option_46="Groundwater pollution"
    option_47="Physical-chemical properties of soils and land use"
    option_48="Air forecast"
    option_49="Air chemistry and transport forecast"
    option_50="Agricultural soil quality"
    option_51="Air quality: air pollution"
    option_52="Quality of coastal waters"
    option_53="Air quality"
    option_54="Air quality in institutions receiving public"
    option_55="Air quality and Bruit"
    option_56="Air quality and acoustic"
    option_57="Water quality"
    option_58="Water quality"
    option_59="Surface water quality / Knowledge media"
    option_60="Soil quality"
    option_61="Urban soil quality"
    option_62="Radioactivity"
    option_63="Radio frequency"
    option_64="Radon emitted by geological formations"
    option_65="Ionizing radiation"
    option_66="Natural sites/ Biodiversity Census"
    option_67="Water mass standard"
    option_68="French Hydrographic Standards"
    option_69="French Hydrogeological Standards"
    option_70="Station measurement networks"
    option_71="Polluted sites and soils"
    option_72="Road traffic"
    option_73="Sales of phytopharmaceutical products"
    

class Exposure_Factor_CategoryEnumFr(str, Enum):
    option_1="ondes radioélectriques"
    option_2="polluants de l'alimentation"
    option_3="bruit"
    option_4="indicateurs socio-démographiques"
    option_5="polluants de l’air"
    option_6="polluants de l'eau de boisson"
    option_7="métaux"
    option_8="polluants de l'air intérieur"
    option_9="facteurs météorologiques"
    option_10="déchets"
    option_11="pesticides"
    option_12="biocides"
    option_13="polluants de l'eau"
    option_14="polluants des sols"
    option_15="ndvi"
    option_16="amiante"
    option_17="radioactivité"
    option_18="air"
    option_19="exposition professionnelles"
    option_20="produits et substances phytopharmaceutiques"
    option_21="radiation"
    option_22="composés organiques"
    
class Exposure_Factor_CategoryEnumEn(str, Enum):
    option_1="radio waves"
    option_2="alimentation pollution"
    option_3="noise"
    option_4="sociodemographical indicators"
    option_5="air pollution"
    option_6="drinking water pollution"
    option_7="metals"
    option_8="indoor air pollution"
    option_9="meteorological factors"
    option_10="waste"
    option_11="pesticides"
    option_12="biocides"
    option_13="water pollution"
    option_14="soils pollution"
    option_15="nvdi"
    option_16="asbestos"
    option_17="radioactivity"
    option_18="air"
    option_19="professional exposure"
    option_20="plant protection products and substances"
    option_21="radiation"
    option_22="organic compounds"
    

class Theme_CategoryEnumFr(str, Enum):
    option_1="Agriculture, pêche, sylviculture et alimentation"
    option_2="Environnement"
    option_3="Population et société"
    option_4="Régions et villes"
    option_5="Santé"
    option_6="Transports"
    
class Theme_CategoryEnumEn(str, Enum):
    option_1="Agriculture and Fisheries"
    option_2="Environment"
    option_3="Population and Society"
    option_4="Regions and Cities"
    option_5="Health"
    option_6="Transport"
    

class License_NameEnumFr(str, Enum):
    option_1="CC-BY-NC-SA"
    option_2="CC0"
    option_3="Licence Ouverte"
    option_4="Licence Ouverte Etalab"
    option_5="SINP"
    option_6="Non renseigné"
    option_7="OdbL"
    
class License_NameEnumEn(str, Enum):
    option_1="CC-BY-NC-SA"
    option_2="CC0"
    option_3="Open License"
    option_4="Open License Etalab"
    option_5="SINP"
    option_6="Not Specified"
    option_7="OdbL"
    

class License_TypeEnumFr(str, Enum):
    option_1="Attribution"
    option_2="Domaine publique"
    option_3="Effet viral (alias Share-Alike)"
    option_4="A usage non commercial seulement"
    option_5="Aucun travail dérivé"
    option_6="Droits d'auteur requis"
    option_7="Noms réservés / Approbation / Statut officiel"
    option_8="Coût nominal"
    option_9="Rétrocéder"
    option_10="Compétence dans l'UE"
    option_11="Autres clauses restrictives"
    option_12="Charge de brevet connue"
    option_13="Droits de propriété intellectuelle inconnus"
    
class License_TypeEnumEn(str, Enum):
    option_1="Attribution"
    option_2="PublicDomain"
    option_3="ViralEffect-ShareAlike"
    option_4="NonCommercialUseOnly"
    option_5="NoDerivativeWork"
    option_6="RoyaltiesRequired"
    option_7="ReservedNames-Endorsement-OfficialStatus"
    option_8="NominalCost"
    option_9="GrantBack"
    option_10="JurisdictionWithinTheEU"
    option_11="OtherRestrictiveClauses"
    option_12="KnownPatentEncumbrance"
    option_13="UnknownIPR"
    

class Data_FormatEnumFr(str, Enum):
    option_1="pdf"
    option_2="date"
    option_3="binaire"
    option_4="texte"
    option_5="rapport"
    option_6="xls"
    option_7="csv"
    option_8="integer"
    option_9="ascii"
    option_10="cartographie"
    option_11="vector"
    option_12="nombres"
    option_13="ods"
    option_14="carte"
    option_15="chiffres"
    option_16="image"
    
class Data_FormatEnumEn(str, Enum):
    option_1="pdf"
    option_2="date"
    option_3="binary"
    option_4="text"
    option_5="reporting"
    option_6="xls"
    option_7="csv"
    option_8="integer"
    option_9="ascii"
    option_10="cartography"
    option_11="vector"
    option_12="numbers"
    option_13="ods"
    option_14="map"
    option_15="digits"
    option_16="image"
    

class Data_DomainEnumFr(str, Enum):
    option_1="Environnement"
    option_2="Santé"
    option_3="Référentiel"
    
class Data_DomainEnumEn(str, Enum):
    option_1="Environment"
    option_2="Health"
    option_3="Standards"
    

class Broadcast_ModeEnumFr(str, Enum):
    option_1="API"
    option_2="Process"
    option_3="Portail"
    
class Broadcast_ModeEnumEn(str, Enum):
    option_1="API"
    option_2="Process"
    option_3="Portal"
    

class Geographical_Geospatial_Information_LevelEnumFr(str, Enum):
    option_1="1/25 000"
    option_2="1/1 000 000"
    option_3="Maillage 25ha/25ha"
    option_4="Canton"
    option_5="Carreau 2km/2km"
    option_6="Commune"
    option_7="IRIS"
    option_8="Parcelle"
    option_9="UDI"
    option_10="Département"
    option_11="Code INSEE"
    option_12="Canton"
    option_13="Station de mesure"
    option_14="Petites régions agricoles"
    option_15="Région"
    option_16="EPCI"
    option_17="Adresse"
    option_18="Etablissement"
    option_19="France entière"
    option_20="Métropole ou DOM"
    option_21="Installations"
    option_22="Latitude/Longitude"
    option_23="Maillage 16 km/16 km"
    option_24="Maillage 2km/2km"
    option_25="Non renseigné"
    option_26="Parc nationaux"
    option_27="Parcelle"
    option_28="Point de mesure"
    option_29="Commune"
    option_30="Coordonnées x/y"
    option_31="Points de mesure"
    option_32="Maillage 1km/1km"
    option_33="Région"
    option_34="Site de mesure"
    option_35="Département"
    option_36="Site d'observation"
    option_37="Site de mesure"
    option_38="Site de traitement"
    option_39="Site minier"
    option_40="Siège exploitation agricole"
    option_41="Station de mesure"
    option_42="Antenne"
    option_43="UCS"
    option_44="UTS"
    option_45="1/1 000 000"
    option_46="Ville"
    option_47="Zone"
    option_48="1/50 000"
    option_49="maille 10mx10m"
    option_50="maille 5mx5m"
    option_51="Point d'eau"
    option_52="Etablissement scolaire"
    
class Geographical_Geospatial_Information_LevelEnumEn(str, Enum):
    option_1="1/25 000"
    option_2="1/1 000 000"
    option_3="Maillage 25ha/25ha"
    option_4="Canton"
    option_5="Carreau 2km/2km"
    option_6="Commune"
    option_7="IRIS"
    option_8="Parkelle"
    option_9="UDI"
    option_10="Department"
    option_11="INSEE Code"
    option_12="Canton"
    option_13="Measuring station"
    option_14="Small agricultural areas"
    option_15="Region"
    option_16="EPCI"
    option_17=""Address""
    option_18="Establishment"
    option_19="France whole"
    option_20="Metropolis or DOM"
    option_21="Facilities"
    option_22="Latitude/Longitude"
    option_23="Maillage 16 km/16 km"
    option_24="Maillage 2km/2km"
    option_25="No information"
    option_26="National park"
    option_27="Parkelle"
    option_28="Measuring point"
    option_29="Commune"
    option_30="Coordinates x/y"
    option_31="Measuring points"
    option_32="Maillage 1km/1km"
    option_33="Region"
    option_34="Measuring site"
    option_35="Department"
    option_36="Observation site"
    option_37="Measuring site"
    option_38="Treatment site"
    option_39="Mining site"
    option_40="Agricultural operations"
    option_41="Measuring station"
    option_42="Antenna"
    option_43="UCS"
    option_44="UTS"
    option_45="1/1 000 000"
    option_46="City"
    option_47="Area"
    option_48="1/50 000"
    option_49="10mx10m"
    option_50="mesh 5mx5m"
    option_51="Water point"
    option_52="School establishment"
    

class Projection_SystemEnumFr(str, Enum):
    option_1="Coordonnées x/y"
    option_2="RGF93"
    option_3="Lambert 93"
    option_4="Lambert 2 étendu"
    option_5="GPS"
    option_6="UTM"
    option_7="WGS84"
    option_8="Non spécifié"
    
class Projection_SystemEnumEn(str, Enum):
    option_1="x/y coordinates"
    option_2="RFG93"
    option_3="Lambert 93"
    option_4="Extended Lambert 2"
    option_5="GPS"
    option_6="UTM"
    option_7="WGS84"
    option_8="Not specified"
    

class Organization_TypeEnumFr(str, Enum):
    option_1="Agence publique"
    option_2="Association déclarée reconnue d'utilité publique"
    option_3="Association loi 1901"
    option_4="Autorité nationale"
    option_5="Autre"
    option_6="Direction ministérielle"
    option_7="EPA"
    option_8="EPI"
    option_9="EPIC"
    option_10="EPST"
    option_11="Ecole d'ingénieur"
    option_12="Etablissement public"
    option_13="GIS"
    option_14="Ministère"
    option_15="Service ministériel"
    option_16="UMS"
    
class Organization_TypeEnumEn(str, Enum):
    option_1="Public Agency"
    option_2="Association of public utility"
    option_3="Association law 1901"
    option_4="National Autority"
    option_5="Other"
    option_6="Ministerial direction"
    option_7="Administrative Public Institution"
    option_8="Industrial Public Institution"
    option_9="Industrial and Commercial Public Institution"
    option_10="Scientific and Technological Public Institution"
    option_11="Engineering School"
    option_12="Public Institution"
    option_13="Group of Scientific  Interest"
    option_14="Ministry"
    option_15="Ministerial Department"
    option_16="Mixed Service Unity"
    

class Agent_TypeEnumFr(str, Enum):
    option_1="Université / Organisation scientifique"
    option_2="Entreprise"
    option_3="Consortium d'industriel"
    option_4="Autorité locale"
    option_5="Autorité nationale"
    option_6="Organisation Non Gouvernementale"
    option_7="Organisation à but non lucratif"
    option_8="Particulier(s)"
    option_9="Autorité régionale"
    option_10="Organisme de normalisation"
    option_11="Autorité supranationale"
    
class Agent_TypeEnumEn(str, Enum):
    option_1="Academia / Scientific Organization"
    option_2="Company"
    option_3="Industry Consortium"
    option_4="LocalAuthority"
    option_5="National Authority"
    option_6="Non Governmental Organization"
    option_7="Non Profit Organization"
    option_8="Private Individual(s)"
    option_9="Regional Authority"
    option_10="Standardization Body"
    option_11="Supra National Authority"
    

class ActionEnumFr(str, Enum):
    option_1="créer"
    option_2="supprimer"
    option_3="éditer"
    option_4="commenter"
    option_5="suggérer"
    option_6="ajouter"
    
class ActionEnumEn(str, Enum):
    option_1="create"
    option_2="delete"
    option_3="edit"
    option_4="comment"
    option_5="suggest"
    option_6="add"
    

class PerimeterEnumFr(str, Enum):
    option_1="jeu de données"
    option_2="organisme"
    option_3="utilisateur"
    option_4="rôle"
    option_5="référence"
    option_6="commentaire"
    
class PerimeterEnumEn(str, Enum):
    option_1="dataset"
    option_2="organization"
    option_3="user"
    option_4="role"
    option_5="reference"
    option_6="comment"
    
    

class Reference(BaseModel):
    name_en: str
    name_fr: str
    uri: Optional[HttpUrl]
    slug: Optional[str]
    table_name: str
    